
export const models: { [key: string]: string } = {
    'icosphere': require('../../res/models/icosphere.obj'),
    'icosphere_smooth': require('../../res/models/icosphere_smooth.obj'),
    'uvsphere': require('../../res/models/uvsphere.obj'),
    'uvsphere_smooth': require('../../res/models/uvsphere_smooth.obj'),
    'cube': require('../../res/models/cube.obj'),
    'torus': require('../../res/models/torus.obj'),
    'monkey': require('../../res/models/monkey.obj'),
    'suzanne': require('../../res/models/suzanne.obj'),
    'suzanne_smooth': require('../../res/models/suzanne_smooth.obj'),
    'suzanne_smoother': require('../../res/models/suzanne_smoother.obj'),
    'suzanne_smoothest': require('../../res/models/suzanne_smoothest.obj'),
    'bunny': require('../../res/models/bunny.obj'),
    'cruiser': require('../../res/models/cruiser.obj'),
    'toyplane': require('../../res/models/toyplane.obj'),
    'teapot': require('../../res/models/teapot.obj'),
    'tea_spoon': require('../../res/models/tea_spoon.obj'),
    'menger_sponge': require('../../res/models/menger_sponge.obj'),
    'gear': require('../../res/models/gear.obj'),
    'wall': require('../../res/models/wall.obj'),
    'triangle': require('../../res/models/triangle.obj'),
};